name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pnpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, build]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run Script ${{ matrix.script }}
        run: pnpm ${{ matrix.script }}

  lint-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Lint docs links
        run: pnpm lint:links
